server:
  port: 5000
spring:
  redis:
    host: 8.130.186.44
    port: 6379
    password: 123456 #redis数据库索引
    database: 1
  datasource:
    url: jdbc:mysql://8.130.186.44:3306/tudou_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: tudou_test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
